# Generated by Django 4.2.6 on 2024-01-26 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='profile_pic',
            field=models.ImageField(blank=True, default='app/uploads/user-default.jpeg', null=True, upload_to='app/uploads/'),
        ),
        migrations.AlterField(
            model_name='properties',
            name='picture',
            field=models.ImageField(blank=True, default='app/uploads/default.png', null=True, upload_to='app/uploads/'),
        ),
    ]
